name = "Tonari"
uuid = "91081016-e225-4157-90a8-4c5abf36a564"
authors = ["Mehdy Lefkir"]
version = "0.2.0"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Aqua = "0.8"
CFITSIO = "1.7.1"
CSV = "0.10.15"
CairoMakie = "0.13.7"
DataFrames = "1.7.0"
DelimitedFiles = "1.9"
DimensionalData = "0.29.17"
Distributions = "0.25"
FFTW = "1"
FHist = "0.11.10"
FITSIO = "0.17.5"
Interpolations = "0.15, 0.16"
ProgressMeter = "1.10.2"
Random = "1"
ReverseDiff = "1.16.1"
StatsBase = "0.34"
Test = "1"
Unitful = "1.22.0"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "DelimitedFiles"]
